version: "3.7"
services:
  app:
    build:
      args:
        user: bani
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: landing
    container_name: landing-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - landing

  nginx:
    image: nginx:alpine
    container_name: landing-nginx
    restart: unless-stopped
    ports:
      - ${APPLICATION_PORT}:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - landing

networks:
  landing:
    driver: bridge
